# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-23 23:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_placement',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=50)),
                ('selected_team', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Login_detail',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('customer_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=50)),
                ('brief_description', models.CharField(max_length=50)),
                ('full_description', models.CharField(max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('Ateams', models.CharField(max_length=50)),
                ('A_odds', models.FloatField()),
                ('Draws', models.CharField(default='Draw', max_length=50)),
                ('Draw', models.FloatField(default=1.5)),
                ('Bteams', models.CharField(max_length=50)),
                ('B_odds', models.FloatField()),
            ],
        ),
    ]
