# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-25 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetApp', '0002_auto_20161224_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='team',
            name='Draw',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='Draws',
            field=models.CharField(max_length=50),
        ),
    ]
